# Generated by Django 4.2.2 on 2023-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemno", models.CharField(max_length=50)),
                ("itemdescription", models.CharField(max_length=50)),
                ("itembarcode", models.CharField(max_length=50)),
                ("itemuom", models.CharField(max_length=50)),
                ("itemcost", models.CharField(max_length=50)),
            ],
        ),
    ]
